<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <script src="/Public/Includes/jquery-3.4.1.min.js" ></script>
    <script src="/Public/Includes/bootstrap.bundle.js" ></script>
    <link rel="stylesheet" href="/Public/Includes/bootstrap.min.css" />
    <link rel="stylesheet" href="/Public/Includes/fontawesome-free-5.13.0-web/css/all.min.css" />
</head>
<body>
<?=$body?>
</body>
</html>